name: Angular CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Run End-to-End Tests
        run: npm run e2e || echo "E2E tests failed, but continuing."

      - name: Build Application
        run: npm run build -- --configuration=production

      - name: Deploy (Only on main branch)
        if: github.ref == 'refs/heads/main'
        run: npm run deploy

name: MJ Cron
